print("\n***** compare numbers *****\n")
print(3 < 4)
print(3 > 4)
print(3 >= 4)
print(3 <= 4)
print(3 >= 3)
print(3 <= 3)
print(3 == 3)
print(3 != 4)

print("\n***** string order *****\n")
print("he" < "hello")
print("he" < "hi")
print("he" < "ha")

print("\n***** boolean operations *****\n")
print(3 < 4 and "he" < "hi")
print((3 < 4) and ("he" < "hi"))
print(not (3 < 4) and not ("he" < "hi"))